spring.application.name=crudapp
spring.config.import=optional:file:.env[.properties]

# Database Configuration from Environment Variables
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME:admin_boot}
spring.datasource.password=${DATABASE_PASSWORD:default_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate ማስተካከያ
spring.jpa.hibernate.ddl-auto=update

# --- DATABASE CONNECTION LOGS IN DETAIL ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=DEBUG
server.port=${SERVER_PORT:8080}

const API_URL = process.env.BACKEND_APP_API_URL 